@startuml
autonumber

actor User as user
participant "Application" as app
participant "GitHub" as github

loop until user quits
    user -> app: challenge request
    app -> github: sample a repo
    github -> app: return the repo information
    app -> user: puzzle
    note left of app: question about filetypes/locations
    user -> app: answer
    app -> user: evaluation
end 
@enduml