title : Software Engineering
author: Maciej Skórski

# Short description
description: >-
  Software engineering laboratory, University of Warsaw 2023.

repository:
  url: https://github.com/maciejskorski/software_engineering
html:
  use_repository_button: true
  google_analytics_id: true

sphinx:
  extra_extensions:
    - sphinxcontrib.mermaid
    - sphinxcontrib.plantuml