title : Software Engineering
author: Maciej Skórski

# Short description
description: >-
  Software engineering laboratory, University of Warsaw 2023.

repository:
  url: https://github.com/{your-book-url}
html:
  use_repository_button: true