name: Java Simple CI

on:
  push:

jobs:
  build-test-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: temurin
    - name: Setup and execute Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
        arguments: |
          check
          build
          test
          --info
        build-root-directory: simpleapp