name: docs

on: [push, pull_request, workflow_dispatch]

jobs:
  docs:
    runs-on: ubuntu-latest
    container: maciejskorski/jupyter-book-extentensions:latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls -a
      - name: Compile Docs
        run: |
          . .venv/bin/activate
          jupyter-book build docs
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/_build/html