name: docs

on: [push, pull_request, workflow_dispatch]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: prepare virtual environment
        run: |
          python -m venv .venv
      - name: cache Python dependencies
        uses: actions/cache@v3
        env:
            cache-name: cache-pip-dependencies
        with:
          path: .venv
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('docs/*') }}
      - name: Install dependencies
        run: |
          source .venv/bin/activate
          sudo apt-get install plantuml
          pip install jupyter-book
          pip install sphinxcontrib-plantuml
      - name: Compile Docs
        run: |
          source .venv/bin/activate
          jupyter-book build docs
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/_build/html
          #destination_dir: docs # match the GitHub Pages repo settings